/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ComponentsImport } from './routes/components'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated/route'
import { Route as IndexImport } from './routes/index'
import { Route as AuthenticatedVisitorManagementRouteImport } from './routes/_authenticated/visitor-management/route'
import { Route as AuthenticatedModulesRouteImport } from './routes/_authenticated/modules/route'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home/route'
import { Route as AuthenticatedAttendanceMonitoringRouteImport } from './routes/_authenticated/attendance-monitoring/route'
import { Route as AuthenticatedAttendanceMonitoringSettingsImport } from './routes/_authenticated/attendance-monitoring/settings'
import { Route as AuthenticatedAttendanceMonitoringDashboardOverviewImport } from './routes/_authenticated/attendance-monitoring/dashboard/overview'
import { Route as AuthenticatedAttendanceMonitoringDashboardEntryExitImport } from './routes/_authenticated/attendance-monitoring/dashboard/entry-exit'
import { Route as AuthenticatedAttendanceMonitoringDashboardDepartmentsImport } from './routes/_authenticated/attendance-monitoring/dashboard/departments'

// Create/Update Routes

const ComponentsRoute = ComponentsImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRouteRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedVisitorManagementRouteRoute =
  AuthenticatedVisitorManagementRouteImport.update({
    id: '/visitor-management',
    path: '/visitor-management',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedModulesRouteRoute = AuthenticatedModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedHomeRouteRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedAttendanceMonitoringRouteRoute =
  AuthenticatedAttendanceMonitoringRouteImport.update({
    id: '/attendance-monitoring',
    path: '/attendance-monitoring',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedAttendanceMonitoringSettingsRoute =
  AuthenticatedAttendanceMonitoringSettingsImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAttendanceMonitoringRouteRoute,
  } as any)

const AuthenticatedAttendanceMonitoringDashboardOverviewRoute =
  AuthenticatedAttendanceMonitoringDashboardOverviewImport.update({
    id: '/dashboard/overview',
    path: '/dashboard/overview',
    getParentRoute: () => AuthenticatedAttendanceMonitoringRouteRoute,
  } as any)

const AuthenticatedAttendanceMonitoringDashboardEntryExitRoute =
  AuthenticatedAttendanceMonitoringDashboardEntryExitImport.update({
    id: '/dashboard/entry-exit',
    path: '/dashboard/entry-exit',
    getParentRoute: () => AuthenticatedAttendanceMonitoringRouteRoute,
  } as any)

const AuthenticatedAttendanceMonitoringDashboardDepartmentsRoute =
  AuthenticatedAttendanceMonitoringDashboardDepartmentsImport.update({
    id: '/dashboard/departments',
    path: '/dashboard/departments',
    getParentRoute: () => AuthenticatedAttendanceMonitoringRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRoute
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/attendance-monitoring': {
      id: '/_authenticated/attendance-monitoring'
      path: '/attendance-monitoring'
      fullPath: '/attendance-monitoring'
      preLoaderRoute: typeof AuthenticatedAttendanceMonitoringRouteImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/modules': {
      id: '/_authenticated/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof AuthenticatedModulesRouteImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/visitor-management': {
      id: '/_authenticated/visitor-management'
      path: '/visitor-management'
      fullPath: '/visitor-management'
      preLoaderRoute: typeof AuthenticatedVisitorManagementRouteImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/attendance-monitoring/settings': {
      id: '/_authenticated/attendance-monitoring/settings'
      path: '/settings'
      fullPath: '/attendance-monitoring/settings'
      preLoaderRoute: typeof AuthenticatedAttendanceMonitoringSettingsImport
      parentRoute: typeof AuthenticatedAttendanceMonitoringRouteImport
    }
    '/_authenticated/attendance-monitoring/dashboard/departments': {
      id: '/_authenticated/attendance-monitoring/dashboard/departments'
      path: '/dashboard/departments'
      fullPath: '/attendance-monitoring/dashboard/departments'
      preLoaderRoute: typeof AuthenticatedAttendanceMonitoringDashboardDepartmentsImport
      parentRoute: typeof AuthenticatedAttendanceMonitoringRouteImport
    }
    '/_authenticated/attendance-monitoring/dashboard/entry-exit': {
      id: '/_authenticated/attendance-monitoring/dashboard/entry-exit'
      path: '/dashboard/entry-exit'
      fullPath: '/attendance-monitoring/dashboard/entry-exit'
      preLoaderRoute: typeof AuthenticatedAttendanceMonitoringDashboardEntryExitImport
      parentRoute: typeof AuthenticatedAttendanceMonitoringRouteImport
    }
    '/_authenticated/attendance-monitoring/dashboard/overview': {
      id: '/_authenticated/attendance-monitoring/dashboard/overview'
      path: '/dashboard/overview'
      fullPath: '/attendance-monitoring/dashboard/overview'
      preLoaderRoute: typeof AuthenticatedAttendanceMonitoringDashboardOverviewImport
      parentRoute: typeof AuthenticatedAttendanceMonitoringRouteImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedAttendanceMonitoringRouteRouteChildren {
  AuthenticatedAttendanceMonitoringSettingsRoute: typeof AuthenticatedAttendanceMonitoringSettingsRoute
  AuthenticatedAttendanceMonitoringDashboardDepartmentsRoute: typeof AuthenticatedAttendanceMonitoringDashboardDepartmentsRoute
  AuthenticatedAttendanceMonitoringDashboardEntryExitRoute: typeof AuthenticatedAttendanceMonitoringDashboardEntryExitRoute
  AuthenticatedAttendanceMonitoringDashboardOverviewRoute: typeof AuthenticatedAttendanceMonitoringDashboardOverviewRoute
}

const AuthenticatedAttendanceMonitoringRouteRouteChildren: AuthenticatedAttendanceMonitoringRouteRouteChildren =
  {
    AuthenticatedAttendanceMonitoringSettingsRoute:
      AuthenticatedAttendanceMonitoringSettingsRoute,
    AuthenticatedAttendanceMonitoringDashboardDepartmentsRoute:
      AuthenticatedAttendanceMonitoringDashboardDepartmentsRoute,
    AuthenticatedAttendanceMonitoringDashboardEntryExitRoute:
      AuthenticatedAttendanceMonitoringDashboardEntryExitRoute,
    AuthenticatedAttendanceMonitoringDashboardOverviewRoute:
      AuthenticatedAttendanceMonitoringDashboardOverviewRoute,
  }

const AuthenticatedAttendanceMonitoringRouteRouteWithChildren =
  AuthenticatedAttendanceMonitoringRouteRoute._addFileChildren(
    AuthenticatedAttendanceMonitoringRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAttendanceMonitoringRouteRoute: typeof AuthenticatedAttendanceMonitoringRouteRouteWithChildren
  AuthenticatedHomeRouteRoute: typeof AuthenticatedHomeRouteRoute
  AuthenticatedModulesRouteRoute: typeof AuthenticatedModulesRouteRoute
  AuthenticatedVisitorManagementRouteRoute: typeof AuthenticatedVisitorManagementRouteRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAttendanceMonitoringRouteRoute:
    AuthenticatedAttendanceMonitoringRouteRouteWithChildren,
  AuthenticatedHomeRouteRoute: AuthenticatedHomeRouteRoute,
  AuthenticatedModulesRouteRoute: AuthenticatedModulesRouteRoute,
  AuthenticatedVisitorManagementRouteRoute:
    AuthenticatedVisitorManagementRouteRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteRouteWithChildren
  '/components': typeof ComponentsRoute
  '/attendance-monitoring': typeof AuthenticatedAttendanceMonitoringRouteRouteWithChildren
  '/home': typeof AuthenticatedHomeRouteRoute
  '/modules': typeof AuthenticatedModulesRouteRoute
  '/visitor-management': typeof AuthenticatedVisitorManagementRouteRoute
  '/attendance-monitoring/settings': typeof AuthenticatedAttendanceMonitoringSettingsRoute
  '/attendance-monitoring/dashboard/departments': typeof AuthenticatedAttendanceMonitoringDashboardDepartmentsRoute
  '/attendance-monitoring/dashboard/entry-exit': typeof AuthenticatedAttendanceMonitoringDashboardEntryExitRoute
  '/attendance-monitoring/dashboard/overview': typeof AuthenticatedAttendanceMonitoringDashboardOverviewRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteRouteWithChildren
  '/components': typeof ComponentsRoute
  '/attendance-monitoring': typeof AuthenticatedAttendanceMonitoringRouteRouteWithChildren
  '/home': typeof AuthenticatedHomeRouteRoute
  '/modules': typeof AuthenticatedModulesRouteRoute
  '/visitor-management': typeof AuthenticatedVisitorManagementRouteRoute
  '/attendance-monitoring/settings': typeof AuthenticatedAttendanceMonitoringSettingsRoute
  '/attendance-monitoring/dashboard/departments': typeof AuthenticatedAttendanceMonitoringDashboardDepartmentsRoute
  '/attendance-monitoring/dashboard/entry-exit': typeof AuthenticatedAttendanceMonitoringDashboardEntryExitRoute
  '/attendance-monitoring/dashboard/overview': typeof AuthenticatedAttendanceMonitoringDashboardOverviewRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/components': typeof ComponentsRoute
  '/_authenticated/attendance-monitoring': typeof AuthenticatedAttendanceMonitoringRouteRouteWithChildren
  '/_authenticated/home': typeof AuthenticatedHomeRouteRoute
  '/_authenticated/modules': typeof AuthenticatedModulesRouteRoute
  '/_authenticated/visitor-management': typeof AuthenticatedVisitorManagementRouteRoute
  '/_authenticated/attendance-monitoring/settings': typeof AuthenticatedAttendanceMonitoringSettingsRoute
  '/_authenticated/attendance-monitoring/dashboard/departments': typeof AuthenticatedAttendanceMonitoringDashboardDepartmentsRoute
  '/_authenticated/attendance-monitoring/dashboard/entry-exit': typeof AuthenticatedAttendanceMonitoringDashboardEntryExitRoute
  '/_authenticated/attendance-monitoring/dashboard/overview': typeof AuthenticatedAttendanceMonitoringDashboardOverviewRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/components'
    | '/attendance-monitoring'
    | '/home'
    | '/modules'
    | '/visitor-management'
    | '/attendance-monitoring/settings'
    | '/attendance-monitoring/dashboard/departments'
    | '/attendance-monitoring/dashboard/entry-exit'
    | '/attendance-monitoring/dashboard/overview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/components'
    | '/attendance-monitoring'
    | '/home'
    | '/modules'
    | '/visitor-management'
    | '/attendance-monitoring/settings'
    | '/attendance-monitoring/dashboard/departments'
    | '/attendance-monitoring/dashboard/entry-exit'
    | '/attendance-monitoring/dashboard/overview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/components'
    | '/_authenticated/attendance-monitoring'
    | '/_authenticated/home'
    | '/_authenticated/modules'
    | '/_authenticated/visitor-management'
    | '/_authenticated/attendance-monitoring/settings'
    | '/_authenticated/attendance-monitoring/dashboard/departments'
    | '/_authenticated/attendance-monitoring/dashboard/entry-exit'
    | '/_authenticated/attendance-monitoring/dashboard/overview'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ComponentsRoute: typeof ComponentsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ComponentsRoute: ComponentsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authenticated",
        "/components"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authenticated": {
      "filePath": "_authenticated/route.tsx",
      "children": [
        "/_authenticated/attendance-monitoring",
        "/_authenticated/home",
        "/_authenticated/modules",
        "/_authenticated/visitor-management"
      ]
    },
    "/components": {
      "filePath": "components.tsx"
    },
    "/_authenticated/attendance-monitoring": {
      "filePath": "_authenticated/attendance-monitoring/route.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/attendance-monitoring/settings",
        "/_authenticated/attendance-monitoring/dashboard/departments",
        "/_authenticated/attendance-monitoring/dashboard/entry-exit",
        "/_authenticated/attendance-monitoring/dashboard/overview"
      ]
    },
    "/_authenticated/home": {
      "filePath": "_authenticated/home/route.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/modules": {
      "filePath": "_authenticated/modules/route.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/visitor-management": {
      "filePath": "_authenticated/visitor-management/route.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/attendance-monitoring/settings": {
      "filePath": "_authenticated/attendance-monitoring/settings.tsx",
      "parent": "/_authenticated/attendance-monitoring"
    },
    "/_authenticated/attendance-monitoring/dashboard/departments": {
      "filePath": "_authenticated/attendance-monitoring/dashboard/departments.tsx",
      "parent": "/_authenticated/attendance-monitoring"
    },
    "/_authenticated/attendance-monitoring/dashboard/entry-exit": {
      "filePath": "_authenticated/attendance-monitoring/dashboard/entry-exit.tsx",
      "parent": "/_authenticated/attendance-monitoring"
    },
    "/_authenticated/attendance-monitoring/dashboard/overview": {
      "filePath": "_authenticated/attendance-monitoring/dashboard/overview.tsx",
      "parent": "/_authenticated/attendance-monitoring"
    }
  }
}
ROUTE_MANIFEST_END */
